import { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    id: 'corredor',
    name: '01. CORREDOR',
    subtitle: 'DESARME E ROUBE ARMAS NO AR COM [E]',
    playerSpawn: [0, 1.7, 12],
    playerYaw: 0,
    initialWeapon: 'pistol',
    initialAmmo: 4,
    enemies: [
      { pos: [0, 0.0, -4], yaw: Math.PI, hasWeapon: true, weaponType: 'pistol' },
      { pos: [2.8, 0.0, -10], yaw: Math.PI + 0.3, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [
      { pos: [-1.8, 0.4, 4], type: 'pistol', ammo: 4 },
    ],
    structures: [
      // Left and Right Hallway Walls
      { type: 'wall', pos: [-4, 3, 0], size: [0.8, 6, 32] },
      { type: 'wall', pos: [4, 3, 0], size: [0.8, 6, 32] },
      // Back and Front Walls
      { type: 'wall', pos: [0, 3, 16], size: [8.8, 6, 0.8] },
      { type: 'wall', pos: [0, 3, -16], size: [8.8, 6, 0.8] },
      // Tactical covers
      { type: 'obstacle', pos: [-1.8, 1.0, 5], size: [1.2, 2.0, 1.2] },
      { type: 'obstacle', pos: [1.8, 1.0, -1], size: [1.2, 2.0, 1.2] },
    ],
  },
  {
    id: 'corpo_a_corpo',
    name: '02. MÃOS LIMPAS',
    subtitle: 'SEM ARMA INICIAL · SOQUE PARA DESARMAR OU ATORDOAR',
    playerSpawn: [0, 1.7, 10],
    playerYaw: 0,
    initialWeapon: null, // Starts unarmed! Must punch or steal
    initialAmmo: 0,
    enemies: [
      { pos: [0, 0.0, 3], yaw: Math.PI, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [-3, 0.0, -6], yaw: Math.PI - 0.4, hasWeapon: true, weaponType: 'pistol' },
      { pos: [3, 0.0, -6], yaw: Math.PI + 0.4, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [],
    structures: [
      { type: 'wall', pos: [-8, 3, 0], size: [0.8, 6, 26] },
      { type: 'wall', pos: [8, 3, 0], size: [0.8, 6, 26] },
      { type: 'wall', pos: [0, 3, 14], size: [16.8, 6, 0.8] },
      { type: 'wall', pos: [0, 3, -14], size: [16.8, 6, 0.8] },
      { type: 'pillar', pos: [-3, 3, 2], size: [1.5, 6, 1.5] },
      { type: 'pillar', pos: [3, 3, 2], size: [1.5, 6, 1.5] },
    ],
  },
  {
    id: 'pilares',
    name: '03. SALA DE PILARES',
    subtitle: 'ARREMECES ATORDÕAM INIMIGOS E DERRUBAM ARMAS',
    playerSpawn: [0, 1.7, 14],
    playerYaw: 0,
    initialWeapon: 'pistol',
    initialAmmo: 4,
    enemies: [
      { pos: [-5, 0.0, 4], yaw: Math.PI - 0.4, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [5, 0.0, 2], yaw: Math.PI + 0.4, hasWeapon: true, weaponType: 'pistol' },
      { pos: [0, 0.0, -8], yaw: Math.PI, hasWeapon: true, weaponType: 'rifle' },
    ],
    pickups: [
      { pos: [-4, 0.4, 10], type: 'pistol', ammo: 3 },
      { pos: [4, 0.4, -2], type: 'shotgun', ammo: 2 },
    ],
    structures: [
      { type: 'wall', pos: [-12, 3.5, 0], size: [1, 7, 36] },
      { type: 'wall', pos: [12, 3.5, 0], size: [1, 7, 36] },
      { type: 'wall', pos: [0, 3.5, 18], size: [25, 7, 1] },
      { type: 'wall', pos: [0, 3.5, -18], size: [25, 7, 1] },
      { type: 'pillar', pos: [-5, 3.5, 8], size: [1.8, 7, 1.8] },
      { type: 'pillar', pos: [5, 3.5, 8], size: [1.8, 7, 1.8] },
      { type: 'pillar', pos: [-5, 3.5, 0], size: [1.8, 7, 1.8] },
      { type: 'pillar', pos: [5, 3.5, 0], size: [1.8, 7, 1.8] },
      { type: 'pillar', pos: [-5, 3.5, -8], size: [1.8, 7, 1.8] },
      { type: 'pillar', pos: [5, 3.5, -8], size: [1.8, 7, 1.8] },
      { type: 'obstacle', pos: [0, 0.8, 0], size: [4, 1.6, 1.2] },
    ],
  },
  {
    id: 'laboratorio',
    name: '04. O MEZANINO',
    subtitle: 'EMBOSCADA DE MÚLTIPLOS ÂNGULOS',
    playerSpawn: [-7, 1.7, 10],
    playerYaw: -0.4,
    initialWeapon: 'shotgun',
    initialAmmo: 2,
    enemies: [
      { pos: [6, 0.0, 6], yaw: -Math.PI / 2, hasWeapon: true, weaponType: 'pistol' },
      { pos: [0, 0.0, -4], yaw: Math.PI, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [-6, 0.0, -10], yaw: Math.PI + 0.6, hasWeapon: true, weaponType: 'rifle' },
      { pos: [6, 0.0, -12], yaw: Math.PI - 0.6, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [
      { pos: [0, 0.4, 7], type: 'rifle', ammo: 6 },
      { pos: [-4, 0.4, -1], type: 'shotgun', ammo: 2 },
      { pos: [4, 0.4, -6], type: 'pistol', ammo: 4 },
    ],
    structures: [
      { type: 'wall', pos: [-14, 4, 0], size: [1, 8, 36] },
      { type: 'wall', pos: [14, 4, 0], size: [1, 8, 36] },
      { type: 'wall', pos: [0, 4, 18], size: [29, 8, 1] },
      { type: 'wall', pos: [0, 4, -18], size: [29, 8, 1] },
      { type: 'obstacle', pos: [0, 1.2, 0], size: [16, 2.4, 2.5] },
      { type: 'obstacle', pos: [-7, 1.2, 5], size: [2, 2.4, 6] },
      { type: 'obstacle', pos: [7, 1.2, -5], size: [2, 2.4, 6] },
      { type: 'obstacle', pos: [-3, 0.9, 10], size: [2.5, 1.8, 1.5] },
      { type: 'obstacle', pos: [3, 0.9, -10], size: [2.5, 1.8, 1.5] },
    ],
  },
  {
    id: 'dojo_briga',
    name: '05. O DOJO CLANDESTINO',
    subtitle: 'PURO COMBATE CORPO A CORPO · COMBO JAB, DIRETO E CRUZADO',
    playerSpawn: [0, 1.7, 11],
    playerYaw: 0,
    initialWeapon: null,
    initialAmmo: 0,
    enemies: [
      { pos: [0, 0.0, 5], yaw: Math.PI, hasWeapon: false },
      { pos: [-3.5, 0.0, 1], yaw: Math.PI - 0.5, hasWeapon: false },
      { pos: [3.5, 0.0, 1], yaw: Math.PI + 0.5, hasWeapon: false },
      { pos: [0, 0.0, -5], yaw: Math.PI, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [],
    structures: [
      { type: 'wall', pos: [-9, 3.5, 0], size: [0.8, 7, 28] },
      { type: 'wall', pos: [9, 3.5, 0], size: [0.8, 7, 28] },
      { type: 'wall', pos: [0, 3.5, 14], size: [18.8, 7, 0.8] },
      { type: 'wall', pos: [0, 3.5, -14], size: [18.8, 7, 0.8] },
      // Ring boundary ropes & mats
      { type: 'obstacle', pos: [-5, 0.6, 0], size: [0.6, 1.2, 16] },
      { type: 'obstacle', pos: [5, 0.6, 0], size: [0.6, 1.2, 16] },
      { type: 'pillar', pos: [-5, 2.5, 8], size: [0.8, 5, 0.8] },
      { type: 'pillar', pos: [5, 2.5, 8], size: [0.8, 5, 0.8] },
      { type: 'pillar', pos: [-5, 2.5, -8], size: [0.8, 5, 0.8] },
      { type: 'pillar', pos: [5, 2.5, -8], size: [0.8, 5, 0.8] },
    ],
  },
  {
    id: 'matriz_hall',
    name: '06. SAGUÃO DA MATRIZ',
    subtitle: 'COLUNAS DE MÁRMORE · LINHAS DE TIRO CRUZADAS',
    playerSpawn: [0, 1.7, 16],
    playerYaw: 0,
    initialWeapon: 'rifle',
    initialAmmo: 12,
    enemies: [
      { pos: [-7, 0.0, 6], yaw: -0.6, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [7, 0.0, 6], yaw: 0.6, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [-5, 0.0, -6], yaw: Math.PI - 0.3, hasWeapon: true, weaponType: 'rifle' },
      { pos: [5, 0.0, -6], yaw: Math.PI + 0.3, hasWeapon: true, weaponType: 'rifle' },
      { pos: [0, 0.0, -12], yaw: Math.PI, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [
      { pos: [0, 0.4, 4], type: 'shotgun', ammo: 4 },
      { pos: [-6, 0.4, 0], type: 'rifle', ammo: 8 },
      { pos: [6, 0.4, 0], type: 'pistol', ammo: 6 },
    ],
    structures: [
      { type: 'wall', pos: [-15, 4.5, 0], size: [1.2, 9, 42] },
      { type: 'wall', pos: [15, 4.5, 0], size: [1.2, 9, 42] },
      { type: 'wall', pos: [0, 4.5, 21], size: [31.2, 9, 1.2] },
      { type: 'wall', pos: [0, 4.5, -21], size: [31.2, 9, 1.2] },
      // Grand double rows of pillars
      { type: 'pillar', pos: [-6, 4.5, 10], size: [2.0, 9, 2.0] },
      { type: 'pillar', pos: [6, 4.5, 10], size: [2.0, 9, 2.0] },
      { type: 'pillar', pos: [-6, 4.5, 2], size: [2.0, 9, 2.0] },
      { type: 'pillar', pos: [6, 4.5, 2], size: [2.0, 9, 2.0] },
      { type: 'pillar', pos: [-6, 4.5, -6], size: [2.0, 9, 2.0] },
      { type: 'pillar', pos: [6, 4.5, -6], size: [2.0, 9, 2.0] },
      // Central security metal detectors
      { type: 'obstacle', pos: [-2, 1.2, 8], size: [1.2, 2.4, 0.6] },
      { type: 'obstacle', pos: [2, 1.2, 8], size: [1.2, 2.4, 0.6] },
    ],
  },
  {
    id: 'cobertura_heliporto',
    name: '07. COBERTURA SUSPENSA',
    subtitle: 'ALTURA VERTICAL E WALLRUNNING OBRIGATÓRIO',
    playerSpawn: [-8, 1.7, 14],
    playerYaw: -0.3,
    initialWeapon: 'pistol',
    initialAmmo: 6,
    enemies: [
      { pos: [8, 0.0, 10], yaw: -Math.PI / 2, hasWeapon: true, weaponType: 'pistol' },
      { pos: [-4, 0.0, 0], yaw: 0, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [6, 0.0, -4], yaw: Math.PI + 0.4, hasWeapon: true, weaponType: 'rifle' },
      { pos: [0, 0.0, -14], yaw: Math.PI, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [-8, 0.0, -10], yaw: Math.PI - 0.4, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [
      { pos: [0, 0.4, 8], type: 'shotgun', ammo: 4 },
      { pos: [0, 0.4, -2], type: 'rifle', ammo: 10 },
    ],
    structures: [
      { type: 'wall', pos: [-16, 5, 0], size: [1, 10, 44] },
      { type: 'wall', pos: [16, 5, 0], size: [1, 10, 44] },
      { type: 'wall', pos: [0, 5, 22], size: [33, 10, 1] },
      { type: 'wall', pos: [0, 5, -22], size: [33, 10, 1] },
      // Elevated catwalk / wallrun ramps
      { type: 'obstacle', pos: [-10, 2.2, 0], size: [3, 4.4, 24] },
      { type: 'obstacle', pos: [10, 2.2, 0], size: [3, 4.4, 24] },
      { type: 'pillar', pos: [0, 5, 0], size: [4, 10, 4] },
      { type: 'obstacle', pos: [0, 1.0, 6], size: [5, 2.0, 1.8] },
      { type: 'obstacle', pos: [0, 1.0, -8], size: [5, 2.0, 1.8] },
    ],
  },
  {
    id: 'matrix_lab',
    name: '08. MATRIX LAB',
    subtitle: 'MÚLTIPLOS ÂNGULOS DE VISÃO · EMBOSCADA EM 3 NÍVEIS',
    playerSpawn: [0, 1.7, 16],
    playerYaw: 0,
    initialWeapon: 'pistol',
    initialAmmo: 4,
    enemies: [
      { pos: [0, 0.0, 6], yaw: Math.PI, hasWeapon: true, weaponType: 'pistol' },
      { pos: [-6, 0.0, -2], yaw: Math.PI / 4, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [6, 0.0, -2], yaw: -Math.PI / 4, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [0, 0.0, -12], yaw: Math.PI, hasWeapon: true, weaponType: 'rifle' },
    ],
    pickups: [
      { pos: [-3, 0.4, 2], type: 'rifle', ammo: 12 },
      { pos: [3, 0.4, 2], type: 'pistol', ammo: 5 },
    ],
    structures: [
      { type: 'wall', pos: [-12, 5, 0], size: [1, 10, 36] },
      { type: 'wall', pos: [12, 5, 0], size: [1, 10, 36] },
      { type: 'wall', pos: [0, 5, 18], size: [25, 10, 1] },
      { type: 'wall', pos: [0, 5, -18], size: [25, 10, 1] },
      // Central multi-tiered computer server monoliths
      { type: 'pillar', pos: [-4, 3, 4], size: [2.5, 6, 2.5] },
      { type: 'pillar', pos: [4, 3, 4], size: [2.5, 6, 2.5] },
      { type: 'pillar', pos: [-4, 3, -6], size: [2.5, 6, 2.5] },
      { type: 'pillar', pos: [4, 3, -6], size: [2.5, 6, 2.5] },
      { type: 'obstacle', pos: [0, 1.2, 0], size: [4, 2.4, 4] },
    ],
  },
  {
    id: 'arena_glitch',
    name: '09. ARENA GLITCH',
    subtitle: 'BATALHA FINAL DE REFLEXOS · O TESTE SUPREMO DO TEMPO',
    playerSpawn: [0, 1.7, 18],
    playerYaw: 0,
    initialWeapon: null, // Pure fist start on final arena
    initialAmmo: 0,
    enemies: [
      { pos: [-4, 0.0, 8], yaw: 0.3, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [4, 0.0, 8], yaw: -0.3, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [-7, 0.0, -4], yaw: Math.PI / 3, hasWeapon: true, weaponType: 'rifle' },
      { pos: [7, 0.0, -4], yaw: -Math.PI / 3, hasWeapon: true, weaponType: 'rifle' },
      { pos: [0, 0.0, -14], yaw: Math.PI, hasWeapon: true, weaponType: 'pistol' },
      { pos: [0, 0.0, 2], yaw: 0, hasWeapon: false }, // Unarmed brawler
    ],
    pickups: [
      { pos: [-4, 0.4, 0], type: 'pistol', ammo: 4 },
      { pos: [4, 0.4, 0], type: 'shotgun', ammo: 5 },
      { pos: [0, 0.4, -6], type: 'rifle', ammo: 15 },
    ],
    structures: [
      { type: 'wall', pos: [-15, 6, 0], size: [1, 12, 42] },
      { type: 'wall', pos: [15, 6, 0], size: [1, 12, 42] },
      { type: 'wall', pos: [0, 6, 21], size: [31, 12, 1] },
      { type: 'wall', pos: [0, 6, -21], size: [31, 12, 1] },
      // Arena obstacles and tactical blocks
      { type: 'pillar', pos: [-6, 5, 6], size: [3, 10, 3] },
      { type: 'pillar', pos: [6, 5, 6], size: [3, 10, 3] },
      { type: 'pillar', pos: [-6, 5, -8], size: [3, 10, 3] },
      { type: 'pillar', pos: [6, 5, -8], size: [3, 10, 3] },
      { type: 'obstacle', pos: [0, 1.4, 5], size: [3, 2.8, 1.5] },
      { type: 'obstacle', pos: [0, 1.4, -4], size: [3, 2.8, 1.5] },
    ],
  },
  {
    id: 'parque_subterraneo',
    name: '10. PARQUE SUBTERRÂNEO',
    subtitle: 'COBERTURA VIDRADA · TIROS RICOS EM ESTRUTURAS FRÁGEIS',
    playerSpawn: [0, 1.7, 12],
    playerYaw: 0,
    initialWeapon: 'rifle',
    initialAmmo: 10,
    enemies: [
      { pos: [-5, 0.0, 4], yaw: Math.PI - 0.3, hasWeapon: true, weaponType: 'pistol' },
      { pos: [5, 0.0, 2], yaw: Math.PI + 0.3, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [0, 0.0, -7], yaw: Math.PI, hasWeapon: true, weaponType: 'rifle' },
      { pos: [-3, 0.0, -11], yaw: Math.PI + 0.2, hasWeapon: true, weaponType: 'pistol' },
      { pos: [3, 0.0, -11], yaw: Math.PI - 0.2, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [
      { pos: [0, 0.4, 6], type: 'shotgun', ammo: 3 },
      { pos: [-4, 0.4, -2], type: 'pistol', ammo: 5 },
    ],
    structures: [
      { type: 'wall', pos: [-12, 4.5, 0], size: [1.2, 9, 38] },
      { type: 'wall', pos: [12, 4.5, 0], size: [1.2, 9, 38] },
      { type: 'wall', pos: [0, 4.5, 19], size: [25.2, 9, 1.2] },
      { type: 'wall', pos: [0, 4.5, -19], size: [25.2, 9, 1.2] },
      { type: 'glass', pos: [-6, 2.8, 0], size: [1.2, 5.6, 20] },
      { type: 'glass', pos: [6, 2.8, 0], size: [1.2, 5.6, 20] },
      { type: 'obstacle', pos: [-2, 1.0, 4], size: [2.5, 2.0, 1.0] },
      { type: 'obstacle', pos: [2, 1.0, -3], size: [2.5, 2.0, 1.0] },
    ],
  },
  {
    id: 'telhado_cidade',
    name: '11. COBERTURA DA CIDADE',
    subtitle: 'PAREDES VERTICAIS · WALLRUN OBRIGATÓRIO · ALTURA EXTREMA',
    playerSpawn: [-9, 1.7, 12],
    playerYaw: -0.2,
    initialWeapon: 'pistol',
    initialAmmo: 6,
    enemies: [
      { pos: [9, 0.0, 10], yaw: -Math.PI / 2, hasWeapon: true, weaponType: 'pistol' },
      { pos: [-4, 0.0, 1], yaw: 0.2, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [5, 0.0, -4], yaw: Math.PI + 0.5, hasWeapon: true, weaponType: 'rifle' },
      { pos: [0, 0.0, -12], yaw: Math.PI, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [-8, 0.0, -9], yaw: Math.PI - 0.4, hasWeapon: true, weaponType: 'rifle' },
    ],
    pickups: [
      { pos: [0, 0.4, 7], type: 'rifle', ammo: 8 },
      { pos: [-3, 0.4, -1], type: 'shotgun', ammo: 3 },
    ],
    structures: [
      { type: 'wall', pos: [-16, 5.5, 0], size: [1, 11, 44] },
      { type: 'wall', pos: [16, 5.5, 0], size: [1, 11, 44] },
      { type: 'wall', pos: [0, 5.5, 22], size: [33, 11, 1] },
      { type: 'wall', pos: [0, 5.5, -22], size: [33, 11, 1] },
      // High platforms / wallrun surfaces
      { type: 'obstacle', pos: [-10, 2.4, 0], size: [3, 4.8, 22] },
      { type: 'obstacle', pos: [10, 2.4, 0], size: [3, 4.8, 22] },
      { type: 'obstacle', pos: [0, 2.4, 7], size: [16, 4.8, 2.5] },
      { type: 'obstacle', pos: [0, 1.0, -7], size: [12, 2.0, 2.0] },
    ],
  },
  {
    id: 'corredor_vidro',
    name: '12. CORREDOR DE VIDRO',
    subtitle: 'TIRO CERTEIRO · VIDRO QUEBRA · CAMINHO LIMPO',
    playerSpawn: [0, 1.7, 14],
    playerYaw: 0,
    initialWeapon: 'shotgun',
    initialAmmo: 3,
    enemies: [
      { pos: [0, 0.0, 5], yaw: Math.PI, hasWeapon: true, weaponType: 'pistol' },
      { pos: [-4, 0.0, -2], yaw: Math.PI + 0.3, hasWeapon: true, weaponType: 'shotgun' },
      { pos: [4, 0.0, -2], yaw: Math.PI - 0.3, hasWeapon: true, weaponType: 'rifle' },
      { pos: [-2, 0.0, -9], yaw: Math.PI + 0.1, hasWeapon: true, weaponType: 'pistol' },
      { pos: [2, 0.0, -9], yaw: Math.PI - 0.1, hasWeapon: true, weaponType: 'pistol' },
    ],
    pickups: [
      { pos: [0, 0.4, 8], type: 'rifle', ammo: 6 },
      { pos: [-3, 0.4, -5], type: 'pistol', ammo: 4 },
    ],
    structures: [
      { type: 'wall', pos: [-10, 4.5, 0], size: [1, 9, 34] },
      { type: 'wall', pos: [10, 4.5, 0], size: [1, 9, 34] },
      { type: 'wall', pos: [0, 4.5, 17], size: [21, 9, 1] },
      { type: 'wall', pos: [0, 4.5, -17], size: [21, 9, 1] },
      { type: 'glass', pos: [0, 2.4, 2], size: [8.5, 4.8, 0.6] },
      { type: 'glass', pos: [0, 2.4, -5], size: [8.5, 4.8, 0.6] },
      { type: 'obstacle', pos: [-3, 1.0, 5], size: [1.2, 2.0, 2.5] },
      { type: 'obstacle', pos: [3, 1.0, -8], size: [1.2, 2.0, 2.5] },
    ],
  },
];

